apiVersion: v1
kind: Service
metadata:
  name: app-b-service
spec:
  selector:
    app: appb
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
  loadBalancerIP: 34.98.117.98 