# Example of the Cloud Build template usage.
#
# In this example, a Cloud Build is triggered with source from a storage bucket.
#
# Replace the following placeholders with valid values:
#   <FIXME:bucket_name>   : a valid storage bucket name (name of an existing 
#                           storage bucket) where the source resides;
#                           e.g.: myapp-source-bucket  
#                           NOTE: do not include neither "gs://" nor trailing slash
#   <FIXME:path_to_source>: a path to the source archive from the root of the bucket;
#                           e.g. docker/mydockerfile.tar.gz
#                           NOTE: source files must be uploaded as a gzip compressed 
#                           tar archive
#   <FIXME:builder_name>  : a cloud-builder supported on Google Cloud;
#                           see details at 
#                           https://cloud.google.com/cloud-build/docs/cloud-builders
#   <FIXME:build_args>    : a list of build arguments supported by the builder;
#                           enter each argument on a separate line as show below
#   Example build step:
#     - name: 'gcr.io/cloud-builders/git'
#       args:
#         - clone
#         - https://github.com/GoogleCloudPlatform/deploymentmanager-samples

imports:
  - path: templates/cloudbuild/cloudbuild.py
    name: build.py

resources:
  - name: mycloudbuild
    type: build.py
    properties:
      source:
        storageSource:
          bucket: <FIXME:bucket_name>
          object: <FIXME:path_to_source>
      steps:
        - name: 'gcr.io/cloud-builders/<FIXME:builder_name>'
          args:
            - <FIXME:build_args>
            - <FIXME:build_args>
        - name: 'gcr.io/cloud-builders/<FIXME:builder_name>'
          args:
            - <FIXME:build_args>
            - <FIXME:build_args>
      timeout: '200s'
