# Example of the Cloud Build template usage.
#
# In this example, a Build is launched for the following Github repo.
# https://github.com/GoogleCloudBuild/gcbapp-example
#
# Pre-requisites steps for this build example: 
# Step1: Login to github and fork the following github repo
#        https://github.com/GoogleCloudBuild/gcbapp-example
# Step2: Create a Cloud Source repo, name your repo
#        After the repo is created successfully do the following     
#        - Select "Automatically mirror from Github/Bitbucket" option
#        - Select "Hosting Service", Choose "Github" from dropdown then Connect
#        - Follow steps to Authenticate your Github repo
#        - Once authenticated, select the repo (from Step1) from the list
#        - Select, "I consent .." checkbox then Click "connect"
# Step3: Replace <FIXME:repo_name> with the repo name created in Step2
#

imports:
  - path: templates/cloudbuild/cloudbuild.py
    name: build.py

resources:
  - name: mycloudbuild
    type: build.py
    properties:
      source:
        repoSource:
          repoName: '<FIXME:repo_name>'
          branchName: 'master'
      steps:
        - name: 'gcr.io/cloud-builders/docker'
          args:
            - 'build'
            - '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'
            - '.'
        - name: 'gcr.io/cloud-builders/docker'
          args:
            - 'push'
            - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
      substitutions:
        _IMAGE_NAME: '<FIXME:repo_name>'
      images:
        - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
      timeout: '600s'
