# Example of the runtime config template usage.

imports:
  - path: templates/runtime_config/runtime_config.py
    name: runtime_config.py

resources:
  - name: my-test-config
    type: runtime_config.py
    properties:
      config: my-test-config
      description: my config description
      variables:
        - variable: myapp/dev/sql/connection_string
          text: super text value
        - variable: myapp/dev/web/wildcardcert
          value: c3VwZXJhd2Vzb21ldGV4dAo=
      waiters:
        - waiter: my-test-waiter
          timeout: 3.5s
          success:
            cardinality:
              path: myapp/dev
              number: 2
