apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
        version: "2"
    spec:
      containers:
      - image: nginx
        name: nginx-container
        ports:
        - containerPort:  
          name: http
          protocol: TCP
      - image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
          name: tcp
          protocol: TCP
