imports:
- path: bigtable.py

resources:
- name: my-bigtable
  type: bigtable.py
  properties:
    instanceId: my-instance
    instance:
      displayName: My BigTable Instance.
      type: PRODUCTION
    clusters:
      initial:
        defaultStorageType: HDD
        # Can only specify serveNodes when instance type is not DEVELOPMENT
        serveNodes: 4
        location: us-central1-b
    tables:
      data:
        granularity: MILLIS
        columnFamilies:
          foo:
            gcRule:
              maxNumVersions: 2
          bar:
            gcRule:
              maxNumVersions: 2
      users:
        columnFamilies:
          username:
            gcRule:
              maxNumVersions: 2
          email:
            gcRule:
              maxNumVersions: 2
