apiVersion: v1
kind: Service
metadata:
  name: appa
spec:
  selector:
    app: appa
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: 34.98.117.98 