apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
