imports:
  - path: clone_cloud_sql.py

resources:
  - name: new-instance
    type: clone_cloud_sql.py
    properties:
        instanceToClone: existing-instance
        acquireClonedInstance: true
        acquireProperties:
            settings:
                tier: db-n1-standard-1

